name: StockFolio
options:
  bundleIdPrefix: com.stockfolio
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  groupSortPosition: top
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1"
    INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
    INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
    INFOPLIST_KEY_UILaunchScreen_Generation: YES
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait

targets:
  StockFolio:
    type: application
    platform: iOS
    sources:
      - path: StockFolio
        excludes:
          - "**/.DS_Store"
    resources:
      - path: StockFolio/Resources
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.stockfolio.app
        INFOPLIST_KEY_CFBundleDisplayName: Stock Portfolio
        GENERATE_INFOPLIST_FILE: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor

  StockFolioTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: StockFolioTests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: StockFolio
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.stockfolio.app.tests
        GENERATE_INFOPLIST_FILE: YES

  StockFolioUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: StockFolioUITests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: StockFolio
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.stockfolio.app.uitests
        GENERATE_INFOPLIST_FILE: YES
